// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

const DATABASE_URL =
  Bun.env.NODE_ENV == 'development' ? Bun.env.DATABASE_URL_DEVELOPMENT : Bun.env.DATABASE_URL;

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: env(DATABASE_URL!),
  },
});
